[features]
seeds = false
skip-lint = false
[programs.localnet]
fat_oracle = "835WRKhFSAppy7p4QnFBkXJ6Mec3hAx3Jw2X15JKccyi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/d/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
