[features]
seeds = false
skip-lint = false
[programs.localnet]
fat_oracle = "D2H2soSaRnbPqJaq2QHtD5Lu7fGJMa9mAKwQCCCqHffB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/d/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
