# syntax=docker/dockerfile:1.4
FROM switchboardlabs/sgx-function AS builder

WORKDIR /home/root/
RUN mkdir programs
RUN mkdir programs/oracle-poc
RUN mkdir programs/oracle-poc/src
COPY ./programs/oracle-poc/Cargo.toml  ./programs/oracle-poc
COPY ./programs/oracle-poc/src  ./programs/oracle-poc/src

WORKDIR /home/root/switchboard-function
COPY ./function/Cargo.toml ./function/Cargo.lock ./
COPY ./function/src ./src/

RUN --mount=type=cache,target=/usr/local/cargo/registry,id=${TARGETPLATFORM} \
    --mount=type=cache,target=target,id=${TARGETPLATFORM} \
    cargo build --release && \
    cargo strip && \
    mv target/release/function /sgx/app

FROM switchboardlabs/sgx-function

# Copy the binary
WORKDIR /sgx
COPY --from=builder /sgx/app /sgx

# Get the measurement from the enclave
RUN rm -f /measurement.txt
RUN /get_measurement.sh && \
    cat /measurement.txt

ENTRYPOINT ["bash", "/boot.sh"]
